### PR TITLE
Added Nightmare boss

### PR DESCRIPTION
**Pull request by kylemiller3**

### CODE REVIEW

**Comment by kylemiller3** [comment]
Can you push this to npm?

**Comment by Judaxx** [comment]
> Can you push this to npm?

Whoops, forgot it again. My bad.

I'll look into setting up github actions to automatically publish the changes to npm if the master branch is updated. Not sure if it's possible, but worth a try.

Thanks

**Comment by kylemiller3** [comment]
Did you bump the version for npm or is 1.2.3 current?

**Comment by kylemiller3** [comment]
Oh some reason I didn't see 1.3.0

**Pull request merged**
